### ISSUE TITLE
Iterative deepening search instead of breadth first?

### ISSUE THREAD

**Issue by lukas-jung** [LhKipp/Prolog_BFS#28]
hey.
i'm not an expert on prolog, but I think bfs means O(2^d) space complexity, d being the depth of the tree.

with iterative deepening depth first search you should get the same time complexity but O(d) space complexity, if i'm not mistaken.

https://en.wikipedia.org/wiki/Iterative_deepening_depth-first_search

Have you considered this?

I guess that could solve the problems with limited ram in the wasm version and things like that.

**Comment by LhKipp** [comment]
Thanks, yes I considered this. This project is about implementing Prolog with a bfs strategy.
